// apps/react-app-container/src/components/remote/index.tsx
import getRemoteScript from "@repe/remote-utils";
import { useEffect, useRef } from "react";

interface Attrs {
	name: string;
	hello: () => void;
}

interface IProps {
	mfName: string;
	module: string;
	attrs: Attrs;
}

const RemoteComp = (props: IProps) => {
	const ref = useRef(null);
	const { mfName, module, attrs } = props;

	const getComp = async () => {
		const REMOTE_URL = process.env.REACT_APP_VUE_REMOTE_URL;
		// import 远程挂载vue组件的方法
		const { mountComponentMain } = (await getRemoteScript(
			`${REMOTE_URL}/remoteEntry.js`,
			mfName,
			"./VueMountComponentMain",
		)) as unknown as {
			mountComponentMain: (compName: any, targetEl: any, attrs: any) => void;
		};
		// import 远程组件
		const result = await getRemoteScript(
			`${REMOTE_URL}/remoteEntry.js`,
			mfName,
			module,
		);

		mountComponentMain(result, ref.current, {
			props: {
				name: attrs.name,
			},
			on: {
				hello: attrs.hello,
			},
		});
	};
	useEffect(() => {
		getComp();
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	return <div ref={ref}>RemoteComp</div>;
};

export default RemoteComp;

// apps/vue-app/src/components/Remote/index.vue
<template>
	<div ref="root">Loading...</div>
</template>

<script>
import { getRemoteScript, reactInVue } from "@repe/remote-utils";
export default {
	name: "RemoteComp",
	data() {
		return {
			loading: false,
		};
	},
	props: {
		mfName: {
			type: String,
			required: true,
		},
		module: {
			type: String,
			required: true,
		},
	},
	async mounted() {
		const REMOTE_URL = process.env.VUE_APP_REMOTE_PATH;
		const result = await getRemoteScript(
			`${REMOTE_URL}/remoteEntry.js`,
			this.mfName,
			this.module,
		);
		reactInVue(result, this.$refs.root, {
			...this.$props,
			...this.$listeners,
			...this.$attrs,
		});
	},
};
</script>

<style></style>
